# Generated by Django 5.0.12 on 2025-03-29 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_chatroom_remove_message_room_name_message_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
    ]
